spring.application.name=codechealla

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/codechealla?createDataBaseIfNotExists=true
spring.r2dbc.username=fiappi
spring.r2dbc.password=fiappi
spring.r2dbc.driver-class-name=org.postgresql.Driver

spring.flyway.user=fiappi
spring.flyway.password=fiappi
spring.flyway.schemas=fiappi
spring.flyway.url=jdbc:postgresql://localhost:5432/
spring.flyway.locations=classpath:db/migration